development:
  adapter: postgresql
  encoding: unicode
  database: pkBazar
  host: localhost
  pool: 5
  username: postgres
  password: 123
  port: 5432

test:
    adapter: postgresql
    encoding: unicode
    database: pkBazar
    host: localhost
    pool: 5
    username: postgres
    password: 123
    port: 5432